#!/usr/bin/env bats
#
# Tests for anonymize-firewall.sh script
# Tests firewall rules anonymization functionality, IP and interface anonymization, and consistency

load test_helper

# Path to the anonymize-firewall script
ANONYMIZE_FIREWALL_SCRIPT="${BATS_TEST_DIRNAME}/../scripts/anonymize-firewall.sh"

# Create sample firewall rules file with IPs and interfaces
#
# Creates a firewall rules file with IP addresses and interface names for testing anonymization.
#
# Arguments:
#   $1: Firewall rules file path
create_sample_firewall_file() {
	local rules_file="$1"

	mkdir -p "$(dirname "$rules_file")"

	cat >"$rules_file" <<EOF
# Generated by iptables-save v1.8.7 on Mon Jan 20 10:00:00 2025
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -s 192.168.1.0/24 -j ACCEPT
-A INPUT -s 10.0.0.5 -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i eth1 -o wlan0 -j ACCEPT
-A FORWARD -s 203.0.113.0/24 -d 198.51.100.0/24 -j ACCEPT
COMMIT

*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -o eth0 -j MASQUERADE
-A POSTROUTING -s 192.168.1.0/24 -o eth0 -j SNAT --to-source 203.0.113.1
COMMIT
EOF
}

# Create sample firewall rules file with ipset set names
#
# Creates a firewall rules file with ipset set names for testing set name anonymization.
#
# Arguments:
#   $1: Firewall rules file path
create_sample_firewall_file_with_sets() {
	local rules_file="$1"

	mkdir -p "$(dirname "$rules_file")"

	cat >"$rules_file" <<EOF
# Generated by iptables-save v1.8.7
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
:ALIEN - [0:0]
:TOR - [0:0]
-A INPUT -j ALIEN
-A INPUT -j TOR
-A ALIEN -m set --match-set ALIEN src -j DROP
-A ALIEN -m set --match-set ALIEN_WHITELIST_SRC src -j RETURN
-A TOR -m set --match-set TOR src -j DROP
-A TOR -m set --match-set TOR_WHITELIST_DST dst -j RETURN
-A FORWARD -m set --match-set UBIOS_DMZ_subnets dst -j ACCEPT
-A FORWARD -m set --match-set UBIOS_GUEST_subnets dst -j ACCEPT
COMMIT
EOF
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh exists and is executable" {
	# Purpose: Test verifies that the anonymize-firewall script file exists and has execute permissions
	# Expected: Anonymize-firewall script file is present and executable
	# Importance: Ensures the firewall rules anonymization script can be run directly for rule sanitization
	assert_file_exist "$ANONYMIZE_FIREWALL_SCRIPT"
	assert_file_executable "$ANONYMIZE_FIREWALL_SCRIPT"
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh shows help with --help flag" {
	# Purpose: Test verifies that the anonymize-firewall script displays usage information when --help flag is provided
	# Expected: Script outputs usage information including all available options and flags
	# Importance: Ensures users can access help documentation for script usage and available options
	run bash "$ANONYMIZE_FIREWALL_SCRIPT" --help
	assert_success
	assert_output --partial "Usage:"
	assert_output --partial "anonymize-firewall.sh"
	assert_output --partial "--input"
	assert_output --partial "--output"
	assert_output --partial "--verbose"
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh shows help with -h flag" {
	# Purpose: Test verifies that the anonymize-firewall script displays usage information when -h flag is provided
	# Expected: Script outputs usage information including all available options and flags
	# Importance: Ensures users can access help documentation using the short flag option
	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -h
	assert_success
	assert_output --partial "Usage:"
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh exits with error if input file not found" {
	# Purpose: Test verifies that the anonymize-firewall script validates input file existence before processing
	# Expected: Script exits with failure status and displays error message when input file doesn't exist
	# Importance: Prevents script from attempting to anonymize non-existent files and provides clear error feedback
	local input_file="${TEST_DIR}/nonexistent-rules.txt"

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file"

	assert_failure
	assert_output --partial "Input file not found"
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh exits with error if input file not readable" {
	# Purpose: Test verifies that the anonymize-firewall script validates input file readability before processing
	# Expected: Script exits with failure status and displays error message when input file is not readable
	# Importance: Prevents script from attempting to anonymize unreadable files and provides clear error feedback
	local input_file="${TEST_DIR}/firewall/rules.txt"
	mkdir -p "$(dirname "$input_file")"
	touch "$input_file"
	chmod 000 "$input_file"

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file"

	# Restore permissions for cleanup
	chmod 644 "$input_file" || true

	assert_failure
	assert_output --partial "Input file not readable"
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh exits with error if input file not specified" {
	# Purpose: Test verifies that the anonymize-firewall script requires input file to be specified
	# Expected: Script exits with failure status and displays error message when input file is missing
	# Importance: Prevents script from running without required input and provides clear error feedback
	run bash "$ANONYMIZE_FIREWALL_SCRIPT"

	assert_failure
	assert_output --partial "Input file is required"
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh anonymizes IPv4 addresses" {
	# Purpose: Test verifies that the anonymize-firewall script replaces IP addresses with anonymized versions
	# Expected: Script replaces all IP addresses in firewall rules file with anonymized IPs in 10.x.x.x range
	# Importance: IP anonymization is a core feature for protecting sensitive network information
	local input_file="${TEST_DIR}/firewall/rules.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	create_sample_firewall_file "$input_file"

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file"

	assert_success
	assert_file_exist "$output_file"
	# Verify original IPs are not in output
	refute_file_contains "$output_file" "192.168.1.0"
	refute_file_contains "$output_file" "10.0.0.5"
	refute_file_contains "$output_file" "203.0.113.0"
	refute_file_contains "$output_file" "198.51.100.0"
	refute_file_contains "$output_file" "203.0.113.1"
	# Verify anonymized IPs are in 10.x.x.x range
	run grep -oE '\b10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\b' "$output_file"
	assert_success
	# Verify at least one anonymized IP was found
	assert [ "${#lines[@]}" -gt 0 ]
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh preserves CIDR notation in IP addresses" {
	# Purpose: Test verifies that the anonymize-firewall script preserves CIDR notation when anonymizing IPs
	# Expected: Script replaces IP addresses but preserves CIDR notation (e.g., /24)
	# Importance: Preserving CIDR notation maintains the meaning of network ranges in firewall rules
	local input_file="${TEST_DIR}/firewall/rules.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	create_sample_firewall_file "$input_file"

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file"

	assert_success
	assert_file_exist "$output_file"
	# Verify CIDR notation is preserved (should have /24 in output)
	run grep -E '/24' "$output_file"
	assert_success
	# Verify at least one CIDR notation was found
	assert [ "${#lines[@]}" -gt 0 ]
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh anonymizes interface names" {
	# Purpose: Test verifies that the anonymize-firewall script replaces interface names with anonymized versions
	# Expected: Script replaces all interface names in firewall rules with anonymized interface names
	# Importance: Interface anonymization is a core feature for protecting sensitive network topology information
	local input_file="${TEST_DIR}/firewall/rules.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	create_sample_firewall_file "$input_file"

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file"

	assert_success
	assert_file_exist "$output_file"
	# Verify original interface names are not in output (except lo which is preserved)
	refute_file_contains "$output_file" "eth0"
	refute_file_contains "$output_file" "eth1"
	refute_file_contains "$output_file" "wlan0"
	# Verify lo is preserved (special case)
	assert_file_contains "$output_file" "lo"
	# Verify anonymized interface names are present (should match interface name pattern)
	run grep -oE '(-i|-o) +[a-zA-Z][a-zA-Z0-9_-]+' "$output_file"
	assert_success
	# Verify at least one interface option was found
	assert [ "${#lines[@]}" -gt 0 ]
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh preserves loopback interface name" {
	# Purpose: Test verifies that the anonymize-firewall script preserves the loopback interface name (lo)
	# Expected: Script keeps "lo" as "lo" instead of anonymizing it
	# Importance: Loopback interface is standard and doesn't reveal sensitive information
	local input_file="${TEST_DIR}/firewall/rules.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	mkdir -p "$(dirname "$input_file")"
	cat >"$input_file" <<EOF
*filter
:INPUT DROP [0:0]
-A INPUT -i lo -j ACCEPT
COMMIT
EOF

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file"

	assert_success
	assert_file_exist "$output_file"
	# Verify lo is preserved (use grep with -- to handle pattern starting with -)
	run grep -F -- "-i lo" "$output_file"
	assert_success
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh handles --in-interface and --out-interface options" {
	# Purpose: Test verifies that the anonymize-firewall script handles long-form interface options
	# Expected: Script anonymizes interface names in --in-interface and --out-interface options
	# Importance: Ensures all interface option formats are properly anonymized
	local input_file="${TEST_DIR}/firewall/rules.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	mkdir -p "$(dirname "$input_file")"
	cat >"$input_file" <<EOF
*filter
:INPUT DROP [0:0]
-A INPUT --in-interface eth0 -j ACCEPT
-A FORWARD --out-interface wlan0 -j ACCEPT
COMMIT
EOF

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file"

	assert_success
	assert_file_exist "$output_file"
	# Verify original interface names are not in output
	refute_file_contains "$output_file" "eth0"
	refute_file_contains "$output_file" "wlan0"
	# Verify anonymized interface names are present (use -- to handle pattern starting with --)
	run grep -E -- '--(in|out)-interface' "$output_file"
	assert_success
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh produces consistent anonymization across multiple runs" {
	# Purpose: Test verifies that the anonymize-firewall script produces the same anonymized output when run multiple times
	# Expected: Running the script twice on the same input produces identical output
	# Importance: Consistency ensures that anonymized rules remain understandable and comparable across runs
	local input_file="${TEST_DIR}/firewall/rules.txt"
	local output_file1="${TEST_DIR}/anonymized1.txt"
	local output_file2="${TEST_DIR}/anonymized2.txt"
	create_sample_firewall_file "$input_file"

	# Run anonymization twice
	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file1"
	assert_success

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file2"
	assert_success

	# Verify both output files exist
	assert_file_exist "$output_file1"
	assert_file_exist "$output_file2"

	# Verify outputs are identical
	run diff "$output_file1" "$output_file2"
	assert_success
	assert_output ""
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh handles empty file gracefully" {
	# Purpose: Test verifies that the anonymize-firewall script handles empty firewall rules files without errors
	# Expected: Script processes empty rules file successfully and produces empty output
	# Importance: Ensures script robustness when encountering empty files
	local input_file="${TEST_DIR}/firewall/rules.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	mkdir -p "$(dirname "$input_file")"
	touch "$input_file"
	# Verify file is empty
	assert_file_empty "$input_file"

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file"

	assert_success
	assert_file_exist "$output_file"
	assert_file_empty "$output_file"
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh outputs to stdout when output file not specified" {
	# Purpose: Test verifies that the anonymize-firewall script outputs to stdout when output file is not specified
	# Expected: Script writes anonymized rules content to stdout instead of a file
	# Importance: Enables piping anonymized rules to other commands or viewing directly
	local input_file="${TEST_DIR}/firewall/rules.txt"
	create_sample_firewall_file "$input_file"

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file"

	assert_success
	# Verify output contains anonymized content (should have anonymized IPs)
	assert_output --regexp '10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
	# Verify original IPs are not in output
	refute_output --partial "192.168.1.0"
	refute_output --partial "203.0.113.1"
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh verbose mode shows progress messages" {
	# Purpose: Test verifies that the anonymize-firewall script displays progress messages in verbose mode
	# Expected: Script outputs progress messages indicating anonymization steps when -v flag is provided
	# Importance: Verbose mode helps users understand script progress and troubleshoot anonymization issues
	local input_file="${TEST_DIR}/firewall/rules.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	create_sample_firewall_file "$input_file"

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file" -v

	assert_success
	# Verify verbose messages are present (sent to stderr)
	assert_line --partial "Extracting IPv4 addresses..."
	assert_line --partial "Extracting interface names..."
	assert_line --partial "Anonymizing firewall rules file..."
	assert_line --partial "Anonymization complete!"
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh maps same IP to same anonymized IP consistently" {
	# Purpose: Test verifies that the same IP address is always mapped to the same anonymized IP
	# Expected: Multiple occurrences of the same IP in the rules are all replaced with the same anonymized IP
	# Importance: Ensures consistency within a single anonymization run, making rules understandable
	local input_file="${TEST_DIR}/firewall/rules.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	mkdir -p "$(dirname "$input_file")"
	# Create rules with same IP appearing multiple times
	cat >"$input_file" <<EOF
*filter
:INPUT DROP [0:0]
-A INPUT -s 203.0.113.1 -j ACCEPT
-A INPUT -d 203.0.113.1 -j ACCEPT
-A FORWARD -s 203.0.113.1 -j ACCEPT
COMMIT
EOF

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file"

	assert_success
	# Extract all anonymized IPs that replaced 203.0.113.1
	# They should all be the same
	local ip_count
	ip_count=$(grep -oE '\b10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\b' "$output_file" | wc -l)
	# Should have at least 3 anonymized IPs (one for each occurrence)
	assert [ "$ip_count" -ge 3 ]
	# Verify all occurrences use the same anonymized IP (count unique IPs should be 1)
	local unique_count
	unique_count=$(grep -oE '\b10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\b' "$output_file" | sort -u | wc -l)
	# Since we only have one original IP, all should map to the same anonymized IP
	assert [ "$unique_count" -eq 1 ]
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh maps same interface to same anonymized interface consistently" {
	# Purpose: Test verifies that the same interface is always mapped to the same anonymized interface
	# Expected: Multiple occurrences of the same interface in the rules are all replaced with the same anonymized interface
	# Importance: Ensures consistency within a single anonymization run, making rules understandable
	local input_file="${TEST_DIR}/firewall/rules.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	mkdir -p "$(dirname "$input_file")"
	# Create rules with same interface appearing multiple times
	cat >"$input_file" <<EOF
*filter
:INPUT DROP [0:0]
-A INPUT -i eth0 -j ACCEPT
-A FORWARD -i eth0 -j ACCEPT
-A OUTPUT -o eth0 -j ACCEPT
COMMIT
EOF

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file"

	assert_success
	# Extract all anonymized interface names that replaced eth0
	# They should all be the same
	local iface_count
	iface_count=$(grep -oE '(-i|-o) +[a-zA-Z][a-zA-Z0-9_-]+' "$output_file" | grep -v " lo" | wc -l)
	# Should have at least 3 interface options (one for each occurrence)
	assert [ "$iface_count" -ge 3 ]
	# Verify all occurrences use the same anonymized interface (extract interface names and count unique)
	local unique_count
	unique_count=$(grep -oE '(-i|-o) +[a-zA-Z][a-zA-Z0-9_-]+' "$output_file" | grep -v " lo" | awk '{print $2}' | sort -u | wc -l)
	# Since we only have one original interface (eth0), all should map to the same anonymized interface
	assert [ "$unique_count" -eq 1 ]
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh handles rules file with only IPs (no interfaces)" {
	# Purpose: Test verifies that the anonymize-firewall script handles rules files containing only IP addresses without interface names
	# Expected: Script successfully anonymizes IP addresses even when no interface names are present
	# Importance: Ensures script works with various rule formats and doesn't require interface names
	local input_file="${TEST_DIR}/firewall/rules.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	mkdir -p "$(dirname "$input_file")"
	cat >"$input_file" <<EOF
*filter
:INPUT DROP [0:0]
-A INPUT -s 203.0.113.1 -j ACCEPT
-A INPUT -d 198.51.100.1 -j ACCEPT
-A INPUT -s 192.0.2.1/24 -j ACCEPT
COMMIT
EOF

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file"

	assert_success
	assert_file_exist "$output_file"
	# Verify original IPs are not in output
	refute_file_contains "$output_file" "203.0.113.1"
	refute_file_contains "$output_file" "198.51.100.1"
	refute_file_contains "$output_file" "192.0.2.1"
	# Verify anonymized IPs are present
	run grep -oE '\b10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\b' "$output_file"
	assert_success
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh handles rules file with only interfaces (no IPs)" {
	# Purpose: Test verifies that the anonymize-firewall script handles rules files containing only interface names without IP addresses
	# Expected: Script successfully anonymizes interface names even when no IP addresses are present
	# Importance: Ensures script works with various rule formats and doesn't require IP addresses
	local input_file="${TEST_DIR}/firewall/rules.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	mkdir -p "$(dirname "$input_file")"
	cat >"$input_file" <<EOF
*filter
:INPUT DROP [0:0]
-A INPUT -i eth0 -j ACCEPT
-A FORWARD -i eth1 -o wlan0 -j ACCEPT
-A OUTPUT -o eth0 -j ACCEPT
COMMIT
EOF

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file"

	assert_success
	assert_file_exist "$output_file"
	# Verify original interface names are not in output (except lo)
	refute_file_contains "$output_file" "eth0"
	refute_file_contains "$output_file" "eth1"
	refute_file_contains "$output_file" "wlan0"
	# Verify anonymized interface names are present
	run grep -oE '(-i|-o) +[a-zA-Z][a-zA-Z0-9_-]+' "$output_file"
	assert_success
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh preserves firewall rules file structure" {
	# Purpose: Test verifies that the anonymize-firewall script preserves the structure and formatting of the firewall rules file
	# Expected: Anonymized rules maintain the same line count, table declarations, chain declarations, and COMMIT statements
	# Importance: Preserving rules structure ensures anonymized rules remain readable and parseable
	local input_file="${TEST_DIR}/firewall/rules.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	create_sample_firewall_file "$input_file"

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file"

	assert_success
	# Verify line count is preserved
	local input_lines
	input_lines=$(wc -l <"$input_file")
	local output_lines
	output_lines=$(wc -l <"$output_file")
	assert_equal "$input_lines" "$output_lines"
	# Verify table declarations are preserved
	run grep -E '^\*' "$output_file"
	assert_success
	# Verify chain declarations are preserved
	run grep -E '^:' "$output_file"
	assert_success
	# Verify COMMIT statements are preserved
	run grep -E '^COMMIT' "$output_file"
	assert_success
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh handles multiple tables correctly" {
	# Purpose: Test verifies that the anonymize-firewall script handles multiple iptables tables (filter, nat, etc.)
	# Expected: Script anonymizes IPs and interfaces across all tables while preserving table structure
	# Importance: Real-world firewall rules often span multiple tables
	local input_file="${TEST_DIR}/firewall/rules.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	create_sample_firewall_file "$input_file"

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file"

	assert_success
	assert_file_exist "$output_file"
	# Verify both filter and nat tables are present
	assert_file_contains "$output_file" "*filter"
	assert_file_contains "$output_file" "*nat"
	# Verify COMMIT statements for both tables
	local commit_count
	commit_count=$(grep -c '^COMMIT' "$output_file" || echo "0")
	assert [ "$commit_count" -eq 2 ]
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh handles negated interface options" {
	# Purpose: Test verifies that the anonymize-firewall script handles negated interface options (e.g., -i !eth0)
	# Expected: Script anonymizes interface names in negated options while preserving the negation
	# Importance: Ensures all interface option formats are properly handled
	local input_file="${TEST_DIR}/firewall/rules.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	mkdir -p "$(dirname "$input_file")"
	cat >"$input_file" <<EOF
*filter
:INPUT DROP [0:0]
-A INPUT -i !eth0 -j DROP
-A FORWARD -o !wlan0 -j DROP
COMMIT
EOF

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file"

	assert_success
	assert_file_exist "$output_file"
	# Verify original interface names are not in output
	refute_file_contains "$output_file" "eth0"
	refute_file_contains "$output_file" "wlan0"
	# Verify negation is preserved
	assert_file_contains "$output_file" "!"
	# Verify anonymized interface names are present
	run grep -E '(-i|-o) +!' "$output_file"
	assert_success
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh handles SNAT target with --to-source option" {
	# Purpose: Test verifies that the anonymize-firewall script anonymizes IP addresses in SNAT --to-source options
	# Expected: Script replaces IP addresses in SNAT target options with anonymized IPs
	# Importance: SNAT rules often contain source IP addresses that need anonymization
	local input_file="${TEST_DIR}/firewall/rules.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	mkdir -p "$(dirname "$input_file")"
	cat >"$input_file" <<EOF
*nat
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 192.168.1.0/24 -o eth0 -j SNAT --to-source 203.0.113.1
COMMIT
EOF

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file"

	assert_success
	assert_file_exist "$output_file"
	# Verify original IPs are not in output
	refute_file_contains "$output_file" "203.0.113.1"
	refute_file_contains "$output_file" "192.168.1.0"
	# Verify SNAT target is preserved
	assert_file_contains "$output_file" "SNAT"
	# Verify --to-source is present (use grep with -- to handle pattern starting with --)
	run grep -F -- "--to-source" "$output_file"
	assert_success
	# Verify anonymized IP is present (use -- to handle pattern starting with --)
	run grep -E -- '--to-source 10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' "$output_file"
	assert_success
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh anonymizes ipset set names in firewall rules" {
	# Purpose: Test verifies that the anonymize-firewall script anonymizes ipset set names in --match-set patterns
	# Expected: Set names are replaced with anonymized names (SET_<number> format)
	# Importance: Ensures set names are properly anonymized for privacy
	local input_file="${TEST_DIR}/firewall/rules-with-sets.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	create_sample_firewall_file_with_sets "$input_file"

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file"

	assert_success
	assert_file_exist "$output_file"

	# Verify original set names are not present
	refute_file_contains "$output_file" "ALIEN"
	refute_file_contains "$output_file" "TOR"
	refute_file_contains "$output_file" "UBIOS_DMZ_subnets"
	refute_file_contains "$output_file" "UBIOS_GUEST_subnets"
	refute_file_contains "$output_file" "ALIEN_WHITELIST_SRC"
	refute_file_contains "$output_file" "TOR_WHITELIST_DST"

	# Verify anonymized set names are present (SET_<number> format) (use -- to handle pattern starting with --)
	run grep -E -- '--match-set SET_[0-9]+' "$output_file"
	assert_success
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh maps same set name to same anonymized set name consistently" {
	# Purpose: Test verifies that the same set name is always mapped to the same anonymized set name
	# Expected: Multiple occurrences of the same set name in the rules are all replaced with the same anonymized set name
	# Importance: Ensures consistency within a single anonymization run, making rules understandable
	local input_file="${TEST_DIR}/firewall/rules.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	mkdir -p "$(dirname "$input_file")"
	# Create rules with same set name appearing multiple times
	cat >"$input_file" <<EOF
*filter
:INPUT DROP [0:0]
-A INPUT -m set --match-set ALIEN src -j DROP
-A INPUT -m set --match-set ALIEN dst -j DROP
-A FORWARD -m set --match-set ALIEN src -j DROP
COMMIT
EOF

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file"

	assert_success
	# Extract all anonymized set names that replaced ALIEN
	# They should all be the same
	local set_count
	set_count=$(grep -oE 'SET_[0-9]+' "$output_file" | wc -l)
	# Should have at least 3 anonymized set names (one for each occurrence)
	assert [ "$set_count" -ge 3 ]
	# Verify all occurrences use the same anonymized set name (count unique set names should be 1)
	local unique_count
	unique_count=$(grep -oE 'SET_[0-9]+' "$output_file" | sort -u | wc -l)
	# Since we only have one original set name (ALIEN), all should map to the same anonymized set name
	assert [ "$unique_count" -eq 1 ]
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh uses unified mapping file for set name consistency" {
	# Purpose: Test verifies that the anonymize-firewall script uses unified mapping file for set names
	# Expected: When using a mapping file, same set names map to same anonymized values
	# Importance: Ensures consistency across different anonymization runs and file types
	local input_file="${TEST_DIR}/firewall/rules-with-sets.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	local mapping_file="${TEST_DIR}/mapping.txt"
	create_sample_firewall_file_with_sets "$input_file"

	# First run - create mapping file
	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file" -m "$mapping_file"
	assert_success
	assert_file_exist "$mapping_file"

	# Verify mapping file contains set name mappings
	run grep -E "Set Names:" "$mapping_file"
	assert_success

	# Second run - use existing mapping file
	local output_file2="${TEST_DIR}/anonymized-rules2.txt"
	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file2" -m "$mapping_file"
	assert_success

	# Verify outputs are identical (same mappings used)
	run diff "$output_file" "$output_file2"
	assert_success
	assert_output ""
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh preserves --match-set pattern structure" {
	# Purpose: Test verifies that the anonymize-firewall script preserves the structure of --match-set patterns
	# Expected: Output maintains proper --match-set pattern format with anonymized set names
	# Importance: Ensures anonymized rules remain valid iptables syntax
	local input_file="${TEST_DIR}/firewall/rules-with-sets.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	create_sample_firewall_file_with_sets "$input_file"

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file"

	assert_success
	assert_file_exist "$output_file"

	# Verify --match-set pattern is preserved (use -- to handle pattern starting with -)
	run grep -E -- '-m set --match-set' "$output_file"
	assert_success
	# Verify src/dst options are preserved (use -- to handle pattern starting with --)
	run grep -E -- '--match-set SET_[0-9]+ (src|dst)' "$output_file"
	assert_success
}

# bats test_tags=category:unit
@test "anonymize-firewall.sh handles firewall rules with both set names and IPs" {
	# Purpose: Test verifies that the anonymize-firewall script handles rules containing both set names and IP addresses
	# Expected: Both set names and IP addresses are anonymized correctly
	# Importance: Ensures script works with complex rules containing multiple anonymization targets
	local input_file="${TEST_DIR}/firewall/rules.txt"
	local output_file="${TEST_DIR}/anonymized-rules.txt"
	mkdir -p "$(dirname "$input_file")"
	cat >"$input_file" <<EOF
*filter
:INPUT DROP [0:0]
-A INPUT -s 192.168.1.0/24 -m set --match-set ALIEN src -j DROP
-A INPUT -s 203.0.113.1 -m set --match-set TOR dst -j ACCEPT
COMMIT
EOF

	run bash "$ANONYMIZE_FIREWALL_SCRIPT" -i "$input_file" -o "$output_file"

	assert_success
	assert_file_exist "$output_file"

	# Verify IPs are anonymized
	refute_file_contains "$output_file" "192.168.1.0"
	refute_file_contains "$output_file" "203.0.113.1"

	# Verify set names are anonymized
	refute_file_contains "$output_file" "ALIEN"
	refute_file_contains "$output_file" "TOR"

	# Verify anonymized values are present
	run grep -E 'SET_[0-9]+' "$output_file"
	assert_success
	run grep -E '10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' "$output_file"
	assert_success
}
