#!/usr/bin/env bats
#
# Tests for anonymize-all.sh script
# Tests unified anonymization functionality across all file types with unified mapping
#

load test_helper

# Path to the anonymize-all script
ANONYMIZE_ALL_SCRIPT="${BATS_TEST_DIRNAME}/../scripts/anonymize-all.sh"

# Paths to individual anonymization scripts (for mocking/verification)
ANONYMIZE_FIREWALL_SCRIPT="${BATS_TEST_DIRNAME}/../scripts/anonymize-firewall.sh"
ANONYMIZE_IP_RULES_SCRIPT="${BATS_TEST_DIRNAME}/../scripts/anonymize-ip-rules.sh"
ANONYMIZE_IPSET_SCRIPT="${BATS_TEST_DIRNAME}/../scripts/anonymize-ipset.sh"
ANONYMIZE_LOGS_SCRIPT="${BATS_TEST_DIRNAME}/../scripts/anonymize-logs.sh"

# Create sample files for testing
create_sample_firewall_file() {
	local file="$1"
	mkdir -p "$(dirname "$file")"
	cat >"$file" <<EOF
# Generated by iptables-save
*filter
:INPUT DROP [0:0]
-A INPUT -i eth0 -s 192.168.1.0/24 -j ACCEPT
-A INPUT -m set --match-set ALIEN src -j DROP
COMMIT
EOF
}

create_sample_ipv4_routes_file() {
	local file="$1"
	mkdir -p "$(dirname "$file")"
	cat >"$file" <<EOF
default via 192.168.1.1 dev eth0
10.0.0.0/8 via 10.0.0.1 dev br0
EOF
}

create_sample_ipv6_routes_file() {
	local file="$1"
	mkdir -p "$(dirname "$file")"
	cat >"$file" <<EOF
default via fe80::1 dev eth0
2001:db8::/32 via 2001:db8::1 dev br0
EOF
}

create_sample_ipset_file() {
	local file="$1"
	mkdir -p "$(dirname "$file")"
	cat >"$file" <<EOF
create ALIEN hash:ip family inet hashsize 1024 maxelem 65536
add ALIEN 198.51.100.1
create TOR hash:ip family inet hashsize 1024 maxelem 65536
add TOR 172.16.0.1
EOF
}

create_sample_log_file() {
	local file="$1"
	mkdir -p "$(dirname "$file")"
	cat >"$file" <<EOF
[2025-01-15 10:00:00] [INFO] VPN check for location NYC (203.0.113.1): OK
[2025-01-15 10:01:00] [WARNING] VPN check failed for location DC (198.51.100.1)
EOF
}

# bats test_tags=category:unit
@test "anonymize-all.sh exists and is executable" {
	# Purpose: Test verifies that the anonymize-all script file exists and has execute permissions
	# Expected: Anonymize-all script file is present and executable
	# Importance: Ensures the unified anonymization script can be run directly
	assert_file_exist "$ANONYMIZE_ALL_SCRIPT"
	assert_file_executable "$ANONYMIZE_ALL_SCRIPT"
}

# bats test_tags=category:unit
@test "anonymize-all.sh shows help with --help flag" {
	# Purpose: Test verifies that the anonymize-all script displays usage information when --help flag is provided
	# Expected: Script outputs usage information including all available options and flags
	# Importance: Ensures users can access help documentation for script usage and available options
	run bash "$ANONYMIZE_ALL_SCRIPT" --help
	assert_success
	assert_output --partial "Usage:"
	assert_output --partial "anonymize-all.sh"
	assert_output --partial "--firewall"
	assert_output --partial "--routes-ipv4"
	assert_output --partial "--routes-ipv6"
	assert_output --partial "--ipset"
	assert_output --partial "--logs"
	assert_output --partial "--output-dir"
	assert_output --partial "--mapping-file"
}

# bats test_tags=category:unit
@test "anonymize-all.sh shows help with -h flag" {
	# Purpose: Test verifies that the anonymize-all script displays usage information when -h flag is provided
	# Expected: Script outputs usage information including all available options and flags
	# Importance: Ensures users can access help documentation using the short flag option
	run bash "$ANONYMIZE_ALL_SCRIPT" -h
	assert_success
	assert_output --partial "Usage:"
}

# bats test_tags=category:unit
@test "anonymize-all.sh exits with error if output directory not provided" {
	# Purpose: Test verifies that the anonymize-all script requires output directory
	# Expected: Script exits with failure status and displays error message when output directory is missing
	# Importance: Prevents script from running without proper output configuration
	run bash "$ANONYMIZE_ALL_SCRIPT" -f /tmp/firewall.txt -m /tmp/mapping.txt

	assert_failure
	assert_output --partial "Output directory is required"
}

# bats test_tags=category:unit
@test "anonymize-all.sh exits with error if mapping file not provided" {
	# Purpose: Test verifies that the anonymize-all script requires mapping file
	# Expected: Script exits with failure status and displays error message when mapping file is missing
	# Importance: Ensures unified mapping is always used for consistency
	run bash "$ANONYMIZE_ALL_SCRIPT" -f /tmp/firewall.txt -o /tmp/output

	assert_failure
	assert_output --partial "Mapping file is required"
}

# bats test_tags=category:unit
@test "anonymize-all.sh exits with error if no input files provided" {
	# Purpose: Test verifies that the anonymize-all script requires at least one input file
	# Expected: Script exits with failure status and displays error message when no input files are provided
	# Importance: Prevents script from running without any work to do
	run bash "$ANONYMIZE_ALL_SCRIPT" -o /tmp/output -m /tmp/mapping.txt

	assert_failure
	assert_output --partial "At least one input file must be provided"
}

# bats test_tags=category:unit
@test "anonymize-all.sh exits with error if input file not found" {
	# Purpose: Test verifies that the anonymize-all script validates input file existence
	# Expected: Script exits with failure status and displays error message when input file doesn't exist
	# Importance: Prevents script from attempting to anonymize non-existent files
	run bash "$ANONYMIZE_ALL_SCRIPT" -f /tmp/nonexistent.txt -o /tmp/output -m /tmp/mapping.txt

	assert_failure
	assert_output --partial "Input file(s) not found"
}

# bats test_tags=category:unit
@test "anonymize-all.sh anonymizes firewall rules with unified mapping" {
	# Purpose: Test verifies that the anonymize-all script anonymizes firewall rules using unified mapping
	# Expected: Firewall rules are anonymized and written to output directory with unified mapping
	# Importance: Ensures firewall anonymization works correctly in unified workflow
	local firewall_file="${TEST_DIR}/firewall.txt"
	local output_dir="${TEST_DIR}/output"
	local mapping_file="${TEST_DIR}/mapping.txt"
	create_sample_firewall_file "$firewall_file"

	run bash "$ANONYMIZE_ALL_SCRIPT" -f "$firewall_file" -o "$output_dir" -m "$mapping_file"

	assert_success
	assert_file_exist "${output_dir}/firewall-rules-anonymized.txt"
	assert_file_exist "$mapping_file"
	# Verify mapping file contains mappings
	run grep -E "IPv4 Addresses:" "$mapping_file"
	assert_success
}

# bats test_tags=category:unit
@test "anonymize-all.sh anonymizes IPv4 routes with unified mapping" {
	# Purpose: Test verifies that the anonymize-all script anonymizes IPv4 routes using unified mapping
	# Expected: IPv4 routes are anonymized and written to output directory with unified mapping
	# Importance: Ensures IPv4 route anonymization works correctly in unified workflow
	local routes_file="${TEST_DIR}/routes-ipv4.txt"
	local output_dir="${TEST_DIR}/output"
	local mapping_file="${TEST_DIR}/mapping.txt"
	create_sample_ipv4_routes_file "$routes_file"

	run bash "$ANONYMIZE_ALL_SCRIPT" -r4 "$routes_file" -o "$output_dir" -m "$mapping_file"

	assert_success
	assert_file_exist "${output_dir}/routes-ipv4-anonymized.txt"
	assert_file_exist "$mapping_file"
}

# bats test_tags=category:unit
@test "anonymize-all.sh anonymizes IPv6 routes with unified mapping" {
	# Purpose: Test verifies that the anonymize-all script anonymizes IPv6 routes using unified mapping
	# Expected: IPv6 routes are anonymized and written to output directory with unified mapping
	# Importance: Ensures IPv6 route anonymization works correctly in unified workflow
	local routes_file="${TEST_DIR}/routes-ipv6.txt"
	local output_dir="${TEST_DIR}/output"
	local mapping_file="${TEST_DIR}/mapping.txt"
	create_sample_ipv6_routes_file "$routes_file"

	run bash "$ANONYMIZE_ALL_SCRIPT" -r6 "$routes_file" -o "$output_dir" -m "$mapping_file"

	assert_success
	assert_file_exist "${output_dir}/routes-ipv6-anonymized.txt"
	assert_file_exist "$mapping_file"
}

# bats test_tags=category:unit
@test "anonymize-all.sh anonymizes ipset sets with unified mapping" {
	# Purpose: Test verifies that the anonymize-all script anonymizes ipset sets using unified mapping
	# Expected: Ipset sets are anonymized and written to output directory with unified mapping
	# Importance: Ensures ipset anonymization works correctly in unified workflow
	local ipset_file="${TEST_DIR}/ipset.txt"
	local output_dir="${TEST_DIR}/output"
	local mapping_file="${TEST_DIR}/mapping.txt"
	create_sample_ipset_file "$ipset_file"

	run bash "$ANONYMIZE_ALL_SCRIPT" -s "$ipset_file" -o "$output_dir" -m "$mapping_file"

	assert_success
	assert_file_exist "${output_dir}/ipset-sets-anonymized.txt"
	assert_file_exist "$mapping_file"
}

# bats test_tags=category:unit
@test "anonymize-all.sh anonymizes logs with unified mapping" {
	# Purpose: Test verifies that the anonymize-all script anonymizes logs using unified mapping
	# Expected: Logs are anonymized and written to output directory with unified mapping
	# Importance: Ensures log anonymization works correctly in unified workflow
	local log_file="${TEST_DIR}/vpn-monitor.log"
	local output_dir="${TEST_DIR}/output"
	local mapping_file="${TEST_DIR}/mapping.txt"
	create_sample_log_file "$log_file"

	run bash "$ANONYMIZE_ALL_SCRIPT" -l "$log_file" -o "$output_dir" -m "$mapping_file"

	assert_success
	assert_file_exist "${output_dir}/vpn-monitor-anonymized.log"
	assert_file_exist "$mapping_file"
}

# bats test_tags=category:unit
@test "anonymize-all.sh anonymizes all file types together with unified mapping" {
	# Purpose: Test verifies that the anonymize-all script can anonymize all file types together
	# Expected: All file types are anonymized using the same unified mapping file
	# Importance: Ensures consistent anonymization across all file types
	local firewall_file="${TEST_DIR}/firewall.txt"
	local routes_ipv4_file="${TEST_DIR}/routes-ipv4.txt"
	local routes_ipv6_file="${TEST_DIR}/routes-ipv6.txt"
	local ipset_file="${TEST_DIR}/ipset.txt"
	local log_file="${TEST_DIR}/vpn-monitor.log"
	local output_dir="${TEST_DIR}/output"
	local mapping_file="${TEST_DIR}/mapping.txt"

	create_sample_firewall_file "$firewall_file"
	create_sample_ipv4_routes_file "$routes_ipv4_file"
	create_sample_ipv6_routes_file "$routes_ipv6_file"
	create_sample_ipset_file "$ipset_file"
	create_sample_log_file "$log_file"

	run bash "$ANONYMIZE_ALL_SCRIPT" \
		-f "$firewall_file" \
		-r4 "$routes_ipv4_file" \
		-r6 "$routes_ipv6_file" \
		-s "$ipset_file" \
		-l "$log_file" \
		-o "$output_dir" \
		-m "$mapping_file"

	assert_success

	# Verify all output files exist
	assert_file_exist "${output_dir}/firewall-rules-anonymized.txt"
	assert_file_exist "${output_dir}/routes-ipv4-anonymized.txt"
	assert_file_exist "${output_dir}/routes-ipv6-anonymized.txt"
	assert_file_exist "${output_dir}/ipset-sets-anonymized.txt"
	assert_file_exist "${output_dir}/vpn-monitor-anonymized.log"
	assert_file_exist "$mapping_file"

	# Verify mapping file contains all mapping types
	run grep -E "IPv4 Addresses:" "$mapping_file"
	assert_success
	run grep -E "IPv6 Addresses:" "$mapping_file"
	assert_success
	run grep -E "Set Names:" "$mapping_file"
	assert_success
	run grep -E "Locations:" "$mapping_file"
	assert_success
}

# bats test_tags=category:unit
@test "anonymize-all.sh uses unified mapping for consistency across file types" {
	# Purpose: Test verifies that the anonymize-all script uses unified mapping to ensure same IPs map to same anonymized values
	# Expected: Same IP address appears in multiple files maps to the same anonymized value
	# Importance: Ensures consistency is maintained across all anonymized file types
	local firewall_file="${TEST_DIR}/firewall.txt"
	local ipset_file="${TEST_DIR}/ipset.txt"
	local output_dir="${TEST_DIR}/output"
	local mapping_file="${TEST_DIR}/mapping.txt"

	# Create files with same IP address (192.168.1.1)
	mkdir -p "$(dirname "$firewall_file")"
	cat >"$firewall_file" <<EOF
*filter
-A INPUT -s 192.168.1.1 -j ACCEPT
COMMIT
EOF

	mkdir -p "$(dirname "$ipset_file")"
	cat >"$ipset_file" <<EOF
create TEST_SET hash:ip family inet hashsize 1024 maxelem 65536
add TEST_SET 192.168.1.1
EOF

	run bash "$ANONYMIZE_ALL_SCRIPT" \
		-f "$firewall_file" \
		-s "$ipset_file" \
		-o "$output_dir" \
		-m "$mapping_file"

	assert_success

	# Extract anonymized IP from firewall output
	local anon_ip_firewall
	anon_ip_firewall=$(grep -oE '\b10\.([0-9]{1,3}\.){2}[0-9]{1,3}\b' "${output_dir}/firewall-rules-anonymized.txt" | head -1)

	# Extract anonymized IP from ipset output
	local anon_ip_ipset
	anon_ip_ipset=$(grep -oE '\b10\.([0-9]{1,3}\.){2}[0-9]{1,3}\b' "${output_dir}/ipset-sets-anonymized.txt" | head -1)

	# Verify they are the same (unified mapping)
	assert_equal "$anon_ip_firewall" "$anon_ip_ipset"
}

# bats test_tags=category:unit
@test "anonymize-all.sh creates output directory if it doesn't exist" {
	# Purpose: Test verifies that the anonymize-all script creates output directory if it doesn't exist
	# Expected: Script creates output directory before writing files
	# Importance: Ensures script works even when output directory doesn't exist
	local firewall_file="${TEST_DIR}/firewall.txt"
	local output_dir="${TEST_DIR}/new-output-dir"
	local mapping_file="${TEST_DIR}/mapping.txt"
	create_sample_firewall_file "$firewall_file"

	# Verify directory doesn't exist
	[[ ! -d "$output_dir" ]]

	run bash "$ANONYMIZE_ALL_SCRIPT" -f "$firewall_file" -o "$output_dir" -m "$mapping_file"

	assert_success
	# Verify directory was created
	assert [ -d "$output_dir" ]
	assert_file_exist "${output_dir}/firewall-rules-anonymized.txt"
}

# bats test_tags=category:unit
@test "anonymize-all.sh handles errors gracefully when one script fails" {
	# Purpose: Test verifies that the anonymize-all script handles errors gracefully when one anonymization script fails
	# Expected: Script continues processing other files and reports errors at the end
	# Importance: Ensures partial success scenarios are handled properly
	local firewall_file="${TEST_DIR}/firewall.txt"
	local invalid_file="${TEST_DIR}/invalid.txt"
	local output_dir="${TEST_DIR}/output"
	local mapping_file="${TEST_DIR}/mapping.txt"
	create_sample_firewall_file "$firewall_file"

	# Create invalid file (empty, but will cause error in processing)
	mkdir -p "$(dirname "$invalid_file")"
	touch "$invalid_file"

	# Try to anonymize both - firewall should succeed, invalid file should fail
	# Note: This test may need adjustment based on actual error handling behavior
	run bash "$ANONYMIZE_ALL_SCRIPT" \
		-f "$firewall_file" \
		-r4 "$invalid_file" \
		-o "$output_dir" \
		-m "$mapping_file" || true

	# Firewall should still be anonymized
	assert_file_exist "${output_dir}/firewall-rules-anonymized.txt"
}

# bats test_tags=category:unit
@test "anonymize-all.sh handles verbose mode" {
	# Purpose: Test verifies that the anonymize-all script provides verbose output when -v flag is used
	# Expected: Script outputs additional information about anonymization process when verbose mode is enabled
	# Importance: Helps users understand what anonymization is being performed
	local firewall_file="${TEST_DIR}/firewall.txt"
	local output_dir="${TEST_DIR}/output"
	local mapping_file="${TEST_DIR}/mapping.txt"
	create_sample_firewall_file "$firewall_file"

	run bash "$ANONYMIZE_ALL_SCRIPT" -f "$firewall_file" -o "$output_dir" -m "$mapping_file" -v

	assert_success
	assert_output --partial "Starting unified anonymization"
	assert_output --partial "Mapping file:"
	assert_output --partial "Output directory:"
	assert_output --partial "Anonymizing firewall rules"
	assert_output --partial "Anonymization complete"
}

# bats test_tags=category:unit
@test "anonymize-all.sh loads existing mapping file" {
	# Purpose: Test verifies that the anonymize-all script loads existing mapping file for consistency
	# Expected: When mapping file exists, it is loaded and used for anonymization
	# Importance: Ensures consistency across multiple runs
	local firewall_file="${TEST_DIR}/firewall.txt"
	local output_dir="${TEST_DIR}/output"
	local mapping_file="${TEST_DIR}/mapping.txt"
	create_sample_firewall_file "$firewall_file"

	# Create initial mapping file
	mkdir -p "$(dirname "$mapping_file")"
	cat >"$mapping_file" <<EOF
# Unified Anonymization Mapping
IPv4 Addresses:
--------------------------------------------------
192.168.1.0/24 -> 10.1.2.3/24
EOF

	run bash "$ANONYMIZE_ALL_SCRIPT" -f "$firewall_file" -o "$output_dir" -m "$mapping_file"

	assert_success
	# Verify mapping file was updated (should contain more mappings)
	run grep -E "IPv4 Addresses:" "$mapping_file"
	assert_success
}

# bats test_tags=category:unit
@test "anonymize-all.sh auto-detects files in directory mode" {
	# Purpose: Test verifies that the anonymize-all script auto-detects files when using directory mode
	# Expected: Script finds files matching export patterns and uses them for anonymization
	# Importance: Makes it easier to anonymize exported files without specifying each file explicitly
	local input_dir="${TEST_DIR}/exports"
	local output_dir="${TEST_DIR}/output"
	local mapping_file="${TEST_DIR}/mapping.txt"
	mkdir -p "$input_dir"

	# Create files matching export script patterns
	create_sample_firewall_file "${input_dir}/firewall-rules-2026-01-20-10-00-00.txt"
	create_sample_ipv4_routes_file "${input_dir}/routes-ipv4-2026-01-20-10-00-00.txt"

	run bash "$ANONYMIZE_ALL_SCRIPT" -d "$input_dir" -o "$output_dir" -m "$mapping_file"

	assert_success
	# Verify files were found and anonymized
	assert_file_exist "${output_dir}/firewall-rules-anonymized.txt"
	assert_file_exist "${output_dir}/routes-ipv4-anonymized.txt"
}

# bats test_tags=category:unit
@test "anonymize-all.sh uses most recent file when multiple files exist in directory" {
	# Purpose: Test verifies that directory mode selects the most recent file when multiple matches exist
	# Expected: Script uses the file with the latest timestamp/modification time
	# Importance: Ensures users get the latest exported data when multiple exports exist
	local input_dir="${TEST_DIR}/exports"
	local output_dir="${TEST_DIR}/output"
	local mapping_file="${TEST_DIR}/mapping.txt"
	mkdir -p "$input_dir"

	# Create multiple firewall files with different timestamps
	create_sample_firewall_file "${input_dir}/firewall-rules-2026-01-20-10-00-00.txt"
	sleep 1
	create_sample_firewall_file "${input_dir}/firewall-rules-2026-01-20-11-00-00.txt"

	run bash "$ANONYMIZE_ALL_SCRIPT" -d "$input_dir" -o "$output_dir" -m "$mapping_file"

	assert_success
	# Verify the most recent file was used (should exist and be anonymized)
	assert_file_exist "${output_dir}/firewall-rules-anonymized.txt"
}

# bats test_tags=category:unit
@test "anonymize-all.sh explicit files override directory mode auto-detection" {
	# Purpose: Test verifies that explicitly specified files override auto-detected files from directory
	# Expected: Explicit file arguments take precedence over directory auto-detection
	# Importance: Allows users to mix directory mode with custom files
	local input_dir="${TEST_DIR}/exports"
	local custom_firewall="${TEST_DIR}/custom-firewall.txt"
	local output_dir="${TEST_DIR}/output"
	local mapping_file="${TEST_DIR}/mapping.txt"
	mkdir -p "$input_dir"

	# Create file in directory
	create_sample_firewall_file "${input_dir}/firewall-rules-2026-01-20-10-00-00.txt"
	# Create custom firewall file
	mkdir -p "$(dirname "$custom_firewall")"
	cat >"$custom_firewall" <<EOF
*filter
-A INPUT -s 10.0.0.1 -j ACCEPT
COMMIT
EOF

	run bash "$ANONYMIZE_ALL_SCRIPT" -d "$input_dir" -f "$custom_firewall" -o "$output_dir" -m "$mapping_file"

	assert_success
	# Verify custom file was used (check for 10.0.0.1 anonymization, not 192.168.1.0 from sample)
	assert_file_exist "${output_dir}/firewall-rules-anonymized.txt"
	# Custom file should have been anonymized (10.0.0.1 should be anonymized)
	run grep -v "10.0.0.1" "${output_dir}/firewall-rules-anonymized.txt" || true
	# Should not contain original 10.0.0.1 (it should be anonymized)
	refute_file_contains "${output_dir}/firewall-rules-anonymized.txt" "10.0.0.1"
}

# bats test_tags=category:unit
@test "anonymize-all.sh directory mode provides helpful error when no files found" {
	# Purpose: Test verifies that directory mode provides helpful error message when no matching files are found
	# Expected: Script exits with error and explains what patterns it was looking for
	# Importance: Helps users understand why directory mode failed
	local input_dir="${TEST_DIR}/empty-exports"
	local output_dir="${TEST_DIR}/output"
	local mapping_file="${TEST_DIR}/mapping.txt"
	mkdir -p "$input_dir"

	run bash "$ANONYMIZE_ALL_SCRIPT" -d "$input_dir" -o "$output_dir" -m "$mapping_file"

	assert_failure
	assert_output --partial "No matching files found in directory"
	assert_output --partial "firewall-rules-*.txt"
	assert_output --partial "routes-ipv4-*.txt"
}

# bats test_tags=category:unit
@test "anonymize-all.sh directory mode works with verbose output" {
	# Purpose: Test verifies that directory mode shows auto-detection messages in verbose mode
	# Expected: Verbose mode shows which files were auto-detected
	# Importance: Helps users verify that correct files were found
	local input_dir="${TEST_DIR}/exports"
	local output_dir="${TEST_DIR}/output"
	local mapping_file="${TEST_DIR}/mapping.txt"
	mkdir -p "$input_dir"

	create_sample_firewall_file "${input_dir}/firewall-rules-2026-01-20-10-00-00.txt"
	create_sample_ipv4_routes_file "${input_dir}/routes-ipv4-2026-01-20-10-00-00.txt"

	run bash "$ANONYMIZE_ALL_SCRIPT" -d "$input_dir" -o "$output_dir" -m "$mapping_file" -v

	assert_success
	assert_output --partial "Auto-detecting files in directory"
	assert_output --partial "Found firewall file"
	assert_output --partial "Found IPv4 routes file"
}
